/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zjyu' at '9/30/16 3:07 PM' with Gradle 2.14
 *
 * @author zjyu, @date 9/30/16 3:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
